### PR TITLE
GOK | Add. Update avni-metadata to generate patient identifier, add h…

### PR DESCRIPTION
**Pull request by riyaTw**
…istory and examination, camp ctivity form

### CODE REVIEW

**Comment by mohan-13** [comment]
@riyaTw Can you add some screenshots ?

**Comment by riyaTw** [comment]
Camp Activity
image

**Comment by riyaTw** [comment]
History and Examination Form
image

**Comment by riyaTw** [comment]
Patient Identifier
image

**Review by mohan-13 — APPROVED** [review]

**Pull request merged**
