### PR TITLE
GOK-204 | Add. Audit Log When Accessing E-Sanjeevani Portal

### PR DESCRIPTION
**Pull request by rahu1ramesh**
trello -> [GOK-204](https://trello.com/c/fTxvKgrK)

In this PR, a new report that gives the number of times the E-Sanjeevani portal has been accessed by each of the users. User access is logged when a user clicks on the 'E-Sanjeevani' button, and it has been implemented to facilitate the generation of the E-Sanjevani Teleconsultation Report containing the count of E-Sanjeevani portal visits made by a particular user or Community Health Officer (CHO).

For the logging the portal access, frontend changes have been made and are documented in the following pull request:  https://github.com/Bahmni-HWC/openmrs-module-bahmniapps/pull/6. This pull request enables logging of user access to the E-Sanjeevani Portal.

Below is a sample of the report generated: 
Screenshot 2023-07-24 at 3 31 25 PM

### CODE REVIEW

**Comment by mohan-13** [comment]
I feel `User` column is not needed. Only Name and no.of times would be sufficient

**Comment by rahu1ramesh** [comment]
> I feel `User` column is not needed. Only Name and no.of times would be sufficient

 There is a chance that the combination of `given_name`, `middle_name`, and `family_name` might turn not to be unique.  The use of `User` (username) would give us a unique identifier for each of the user.

**Comment by gokultw** [comment]
> > I feel `User` column is not needed. Only Name and no.of times would be sufficient
> 
> There is a chance that the combination of `given_name`, `middle_name`, and `family_name` might turn not to be unique. The use of `User` (username) would give us a unique identifier for each of the user.

Yes @mohan-13 I have asked him to add both username & Full name to make the rows unique.

**Comment by gsluthra** [comment]
Where is the code that actually creates the Audit Log?

**Comment by gokultw** [comment]
> Where is the code that actually creates the Audit Log?

@gsluthra 
https://github.com/Bahmni-HWC/openmrs-module-bahmniapps/pull/6

**Review by mohan-13 — APPROVED** [review]

**Pull request merged**
