### PR TITLE
Gok 210

### PR DESCRIPTION
**Pull request by deepthi-mantena**
This PR introduces two change sets to add column batch number to inv_item_stock_detail table and outward_id column to inv_stock_operation table.

### CODE REVIEW

**Comment by gsluthra** [comment]
Shouldn't this go into the "omod" liquibase?

**Review by abinaya-u — APPROVED** [review]

**Comment by gokultw** [comment]
@abinaya-u not fixing Gurpreet's comment ?

**Review by gsluthra — CHANGES_REQUESTED** [review]
Please move the liquibase into omod. This is not "configuration" that users can choose. This is schema that omod needs.

**Comment by abinaya-u** [comment]
> Please move the liquibase into omod. This is not "configuration" that users can choose. This is schema that omod needs.
Sure @gsluthra will make the changes

**Comment by deepthi-mantena** [comment]
Missed the comments in the conversation tab as suggested closing this PR from clinic-config we will raise a new PR from the omod's liquibase.

**Pull request closed without merging**
